terraform/cloudflare: add dns for darwin builder
nix-community/infra pull request #348
Opened 2022-12-30 02:08 UTC by zowoq

2022-12-30 11:57 UTC, zimbatm approved these changes

2022-12-30 13:32 UTC, 0x4A6F requested changes

2022-12-30 13:32 UTC, 0x4A6F commented on terraform/cloudflare_nix-community_org.tf
> +  value   = "?"
```diff
-  value   = "?"
+  value   = "167.235.14.165"
```

2022-12-30 13:32 UTC, 0x4A6F commented on terraform/cloudflare_nix-community_org.tf
> +  value   = "?"
Currently there is no AAAA record.

2023-01-10 08:20 UTC, 0x4A6F commented on terraform/cloudflare_nix-community_org.tf
> +  value   = "?"
```diff
-  value   = "?"
+  value   = "2a01:4f8:262:1d98::1"
```

2023-01-10 08:24 UTC, zowoq commented on terraform/cloudflare_nix-community_org.tf
> +  value   = "?"
Thanks.

2023-01-10 08:26 UTC, zowoq commented
bors r+

2023-01-10 08:26 UTC, Mic92 approved these changes

2023-01-10 08:39 UTC, merged